version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: csc460_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: proj_database
      MYSQL_USER: memyselfi
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - csc460_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  python:
    build: .
    container_name: csc460_python
    depends_on:
      database:
        condition: service_healthy
    command: bash ./run_all.sh

volumes:
  csc460_volume:
